### ISSUE TITLE
zone aware balancing question

### ISSUE THREAD

**Issue by ryannguyen** [turbinelabs/rotor#21]
If i wanted to configure envoy to be zone aware, is it correct that i would need a rotor process in each zone?  or can i use a single rotor instance.  thanks!

**Comment by 9len** [comment]
Yes, rotor can only serve a single envoy configuration. You'll need to modify `ROTOR_XDS_STANDALONE_ZONE` for each zone, and you'll need to pass static cluster configs to properly configure the clusters (endpoints can remain dynamic via EDS)

**Comment by ryannguyen** [comment]
@9len Thanks is this still true if I looked into using Houston?

**Comment by 9len** [comment]
@ryannguyen When serving xDS for Houston, Rotor can serve any number of proxies with different configurations, and it's possible to span multiple service discovery collectors. 

Houston supports label-based routing ("subset" routing in Envoy speak), so that you can route to subsets of a cluster based on labels, do canary or blue/green releases etc. The subset load balancer isn't currently compatible with zone-aware load balancing.

Can you tell me a little more about your ZALB use-case?

**Comment by ryannguyen** [comment]
cool.  I'm just looking into it. Our current set up is we have front proxies and clusters set up in aws us-west.  Nodes in a particular cluster are spread evenly across the AZs so looking to take advantage of Envoy's features.

**Comment by 9len** [comment]
cool. closing this for now, let me know if you have any other questions, or if you're interested in talking about Houston more.
