### ISSUE TITLE
Does Rotor's Marathon integration require DC/OS, or would it work with Marathon / Mesos?

### ISSUE THREAD

**Issue by mancini0** [turbinelabs/rotor#4]

**Comment by 9len** [comment]
Hi @mancini0,

It's been a while since we tested the marathon integration, as we haven't yet had any production customers using it. So it probably needs to be dusted off a bit. 

The main question will be around authentication; it was in flux when we wrote the plugin, and there are probably easier ways to auth with service accounts than there were two years ago.

Certainly we'd be happy to help you try it out.
