### ISSUE TITLE
Improve documentation on kubernetes plugin

### ISSUE THREAD

**Issue by chrisgoffinet** [turbinelabs/rotor#8]
It took me a good minute to figure this out, i can definitely see how this will bite first-time users. So I setup rotor + k8s service discovery. I created a pod with the correct labels and yet… nothing. Envoy shows nothing with `config_dump`, and rotor logs were not helpful. So i tried lowering the log level to `debug` for rotor. For some reason my pod was not being picked up. It wasnt until i remembered  from my istio days you need to set the port name to `http`, which when i finally did, rotor picked up the pod. Plus i had to go through source code to confirm this. I think it would be helpful if the project had a simple webserver example in k8s to show this and to call it out. Also i think rotor should at the very least log that a pod was found but because it didnt match `http` it will not be considered. 

Actionable Items
* Provide an example kubernetes pod spec with the correct port labels and cluster label.
* Add better logging to rotor kubernetes plugin to output at INFO that a pod was found but because it did not match the port label (i.e http) it will not be considered. This would really help debug if users make mistakes.

I am happy to do this if you agree its worthwhile.

**Comment by 9len** [comment]
Hi @chrisgoffinet,

Thanks for the thorough description. We document the "http" requirement in our [commercial docs](https://docs.turbinelabs.io/advanced/kubernetes.html) for rotor/kubernetes, but it's a whole in our OSS docs. 

I think what we should do is make a kubernetes directory in examples, move the rotor spec file there, and add an example pod spec file, along with an example envoy-simple spec. We'll handle this work internally, since there is probably some existing copy we can repurpose.

For logging, I agree that when a pod is ignored for whatever reason we should log about it, but I'd rather keep the logs at the debug level, to avoid repetitive logging in the common case. If you're into making that change in the kubernetes collector, I'm all for it! Otherwise we'll do it in the next week or so.

**Comment by 9len** [comment]
The doc stuff was fixed in df37bbaf3f7b2878123fff13a1e15a0f69c6c64a. We'll follow up with a logging change sometime soon.

**Comment by 9len** [comment]
The logging change landed in 369eb69, and is available in rotor 0.17.2
