### ISSUE TITLE
Export a hash for state of the world

### ISSUE THREAD

**Issue by chrisgoffinet** [turbinelabs/rotor#9]
One of the issues I've found through various service mesh technologies is it can be difficult to determine what the current state is for service discovery. Imagine the scenario where you are running multiple Rotor instances for availability purposes. A bug manifests itself in one of the plugins (i.e kubernetes), and let's say the state is now stale (oops we lost the watch and never recovered!). If you are trying to debug a complex service mesh, how would you know? I think it would be extremely valuable to export over the stats backends a deterministic hash of the state of the world. That way when you are monitoring your rotor instances, you can have the confidence that they are sharing the same information across instances to envoy.

My experience is that this is really missing in the service mesh world to help provide debugging when bugs manifest.

**Comment by 9len** [comment]
Hi @chrisgoffinet 

we're actively working on adding some extra rotor-based stats to the stats backend, and we have a version hash derived from the underlying object state, so I think this is workable.

**Comment by 9len** [comment]
@chrisgoffinet I'd like to dig into this use-case a little more. Are you looking for something global across distinctly configured rotors? (eg somehow have the same hash for a rotor collecting consul and a rotor collecting kubernetes). Since each of those rotors might have different internal state, getting them serving the same hash would be difficult.

If you're looking for an export of a hash of what the rotor itself is serving, that's a little simpler. This is basically what is handed out to the Envoys already for Ack/Nack.

When rotor is backed by the TL API, it serves multiple proxy configurations, and each of these has its own hash.

**Comment by chrisgoffinet** [comment]
What rotor itself is serving. I currently have Rotor behind a service in Kubernetes. If i scale the replicas to 3 for availability purposes, I want to make sure those 3 replicas are serving the exact same state out to Envoy. The hash would become important here so that I have confidence there isn't a mismatch. I didn't need to try to compare states across Rotor + Consul, and Rotor + Kubernetes.

**Comment by 9len** [comment]
Got it. Should be doable.
